AzFace/Controllers/RoleAdminController.cs
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using AzFace.Infrastructure;
using AzFace.Models;
using System.Collections.Generic;
using System;
namespace Users.Controllers
{
    public class RoleAdminController : Controller
    {
        public ActionResult Index()
        {
            int personId = Convert.ToInt32(Session["PersonId"]);
            ViewBag.FriendRequestes = FriendHelper.GetFriendRequestes(personId);
            ViewBag.RequestCount = FriendHelper.GetFriendRequestCount(personId);
            ViewBag.MessageCount = FriendHelper.GetMessageCount(personId);
            ViewBag.Messages = FriendHelper.GetMessages(personId);
            return View(RoleManager.Roles);
        }
        public ActionResult Create()
        {
            int personId = Convert.ToInt32(Session["PersonId"]);
            ViewBag.FriendRequestes = FriendHelper.GetFriendRequestes(personId);
            ViewBag.RequestCount = FriendHelper.GetFriendRequestCount(personId);
            ViewBag.MessageCount = FriendHelper.GetMessageCount(personId);
            ViewBag.Messages = FriendHelper.GetMessages(personId);
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create([Required]string name)
        {
            int personId = Convert.ToInt32(Session["PersonId"]);
            ViewBag.FriendRequestes = FriendHelper.GetFriendRequestes(personId);
            ViewBag.RequestCount = FriendHelper.GetFriendRequestCount(personId);
            ViewBag.MessageCount = FriendHelper.GetMessageCount(personId);
            ViewBag.Messages = FriendHelper.GetMessages(personId);
            if (ModelState.IsValid)
            {
                IdentityResult result
                = await RoleManager.CreateAsync(new AppRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }
            return View(name);
        }
        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            int personId = Convert.ToInt32(Session["PersonId"]);
            ViewBag.FriendRequestes = FriendHelper.GetFriendRequestes(personId);
            ViewBag.RequestCount = FriendHelper.GetFriendRequestCount(personId);
            ViewBag.MessageCount = FriendHelper.GetMessageCount(personId);
            ViewBag.Messages = FriendHelper.GetMessages(personId);

            AppRole role = await RoleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await RoleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View("Error", result.Errors);
                }
            }
            else
            {
                return View("Error", new string[] { "Role Not Found" });
            }
        }


        public async Task<ActionResult> Edit(string id)
        {

            int personId = Convert.ToInt32(Session["PersonId"]);
            ViewBag.FriendRequestes = FriendHelper.GetFriendRequestes(personId);
            ViewBag.RequestCount = FriendHelper.GetFriendRequestCount(personId);
            ViewBag.MessageCount = FriendHelper.GetMessageCount(personId);
            ViewBag.Messages = FriendHelper.GetMessages(personId);

            AppRole role = await RoleManager.FindByIdAsync(id);
            string[] memberIDs = role.Users.Select(x => x.UserId).ToArray();
            IEnumerable<AppUser> members
            = UserManager.Users.Where(x => memberIDs.Any(y => y == x.Id));
            IEnumerable<AppUser> nonMembers = UserManager.Users.Except(members);
            return View(new RoleEditModel
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }

        [HttpPost]
        public async Task<ActionResult> Edit(RoleModificationModel model)
        {

            int personId = Convert.ToInt32(Session["PersonId"]);
            ViewBag.FriendRequestes = FriendHelper.GetFriendRequestes(personId);
            ViewBag.RequestCount = FriendHelper.GetFriendRequestCount(personId);
            ViewBag.MessageCount = FriendHelper.GetMessageCount(personId);
            ViewBag.Messages = FriendHelper.GetMessages(personId);

            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (string userId in model.IdsToAdd ?? new string[] { })
                {
                    result = await UserManager.AddToRoleAsync(userId, model.RoleName);
                    if (!result.Succeeded)
                    {
                        return View("Error", result.Errors);
                    }
                }
                foreach (string userId in model.IdsToDelete ?? new string[] { })
                {
                    result = await UserManager.RemoveFromRoleAsync(userId,
                    model.RoleName);
                    if (!result.Succeeded)
                    {
                        return View("Error", result.Errors);
                    }
                }
                return RedirectToAction("Index");
            }
            return View("Error", new string[] { "Role Not Found" });
        }


        
        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (string error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }
        private AppUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppUserManager>();
            }
        }
        private AppRoleManager RoleManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppRoleManager>();
            }
        }
    }
}

AzFace/Views/RoleAdmin/Create.cshtml
@model string
@{ ViewBag.Title = "Create Role";}
<h2>Create Role</h2>
@Html.ValidationSummary(false)
@using (Html.BeginForm())
{
    <div class="form-group">
        <label>Name</label>
        <input name="name" value="@Model" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
}

AzFace/Views/RoleAdmin/Edit.cshtml
@using AzFace.Models
@model RoleEditModel
@{ ViewBag.Title = "Edit Role";}
@Html.ValidationSummary()
@using (Html.BeginForm())
{
    <input type="hidden" name="roleName" value="@Model.Role.Name" />
    <div class="panel panel-primary">
        <div class="panel-heading">Add To @Model.Role.Name</div>
        <table class="table table-striped">
            @if (Model.NonMembers.Count() == 0)
            {
                <tr>
                    <td colspan="2">All Users Are Members</td>
                </tr>
            }
            else
            {
                <tr>
                    <td>User ID</td>
                    <td>Add To Role</td>
                </tr>
                foreach (AppUser user in Model.NonMembers)
                {
                <tr>
                    <td>@user.UserName</td>
                    <td>
                        <input type="checkbox" name="IdsToAdd" value="@user.Id">
                    </td>
                </tr>
                }
            }
        </table>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading">Remove from @Model.Role.Name</div>
        <table class="table table-striped">
            @if (Model.Members.Count() == 0)
            {
                <tr>
                    <td colspan="2">No Users Are Members</td>
                </tr>
            }
            else
            {
                <tr>
                    <td>User ID</td>
                    <td>Remove From Role</td>
                </tr>
                foreach (AppUser user in Model.Members)
                {
                <tr>
                    <td>@user.UserName</td>
                    <td>
                        <input type="checkbox" name="IdsToDelete" value="@user.Id">
                    </td>
                </tr>
                }
            }
        </table>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
}

AzFace/Views/RoleAdmin/Index.cshtml
@using AzFace.Models
@using AzFace.Infrastructure

@model IEnumerable<AppRole>
@{ ViewBag.Title = "Roles"; }
<div class="panel panel-primary">
    <div class="panel-heading">Roles</div>
    <table class="table table-striped">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Users</th>
            <th></th>
        </tr>
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="4" class="text-center">No Roles</td>
            </tr>
        }
        else
        {
            foreach (AppRole role in Model)
            {
            <tr>
                <td>@role.Id</td>
                <td>@role.Name</td>
                <td>
                    @if (role.Users == null || role.Users.Count == 0)
                    {
                        @: No Users in Role
                        }
                    else
                    {
                        <p>@string.Join(", ", role.Users.Select(x => Html.GetUserName(x.UserId)))
                        </p>
                    }
                </td>
                <td>
                    @using (Html.BeginForm("Delete", "RoleAdmin", new { id = role.Id }))
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = role.Id }, new { @class = "btn btn-primary btn-xs" })
                        <button class="btn btn-danger btn-xs"
                            type="submit">
                            Delete
                        </button>
                    }
                </td>
            </tr>
            }
        }
    </table>
</div>
@Html.ActionLink("Create", "Create", null, new { @class = "btn btn-primary" })