AzFace/Controllers/ProfileController.cs
using AzFace.Infrastructure;
using AzFace.Models;
using AzFace.Models.Connection;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;



namespace AzFace.Controllers
{
    public class ProfileController : Controller
    {

        public ActionResult Upload(ProfileViewModel model)
        {
            using (EFPersonRepository db = new EFPersonRepository())
            {
                int personId = Convert.ToInt32(Session["PersonId"]);

                ViewBag.FriendRequestes = FriendHelper.GetFriendRequestes(personId);
                ViewBag.RequestCount = FriendHelper.GetFriendRequestCount(personId);
                ViewBag.MessageCount = FriendHelper.GetMessageCount(personId);
                ViewBag.Messages = FriendHelper.GetMessages(personId);



                var image = WebImage.GetImageFromRequest();

                if (image != null)
                {
                    if (image.Width > 500)
                    {
                        image.Resize(500, ((500 * image.Height) / image.Width));
                    }

                    var filename = Path.GetFileName(image.FileName);
                    image.Save(Path.Combine("~/Images", filename));
                    filename = Path.Combine("~/Images", filename);
                    model.ImageUrl = Url.Content(filename);
                    var editModel = new EditorInputModel()
                       {
                           Profile = model,
                           Width = image.Width,
                           Height = image.Height,
                           Top = image.Height * 0.1,
                           Left = image.Width * 0.9,
                           Right = image.Width * 0.9,
                           Bottom = image.Height * 0.9
                       };
                    return View("Editor", editModel);

                }

                return View("Index", model);
            }
        }

        public ActionResult Edit(EditorInputModel editor)
        {
            using (EFPersonRepository db = new EFPersonRepository())
            {
                int personId = Convert.ToInt32(Session["PersonId"]);

                ViewBag.FriendRequestes = FriendHelper.GetFriendRequestes(personId);
                ViewBag.RequestCount = FriendHelper.GetFriendRequestCount(personId);
                ViewBag.MessageCount = FriendHelper.GetMessageCount(personId);
                ViewBag.Messages = FriendHelper.GetMessages(personId);

                var image = new WebImage("~" + editor.Profile.ImageUrl);
                var height = image.Height;
                var width = image.Width;
                image.Crop((int)editor.Top, (int)editor.Left, (int)(height - editor.Bottom), (int)(width - editor.Right));
                var originalFile = editor.Profile.ImageUrl;
                editor.Profile.ImageUrl = Url.Content("~/ProfileImages/" + Path.GetFileName(image.FileName));
                image.Resize(140, 140, true, false);
                image.Save(@"~" + editor.Profile.ImageUrl);

                Person person = db.People.FirstOrDefault(x => x.PersonId == personId);
                Photo photo = new Photo
                {
                    Person = person,
                    ImageMimeType = image.ImageFormat,
                    ImageType = "profile"
                };
                photo.Image = image.GetBytes();

                person.Photos.Add(photo);
                db.context.SaveChanges();




                System.IO.File.Delete(Server.MapPath(originalFile));
                return RedirectToAction("Index", "Home", null);
            }
        }


        private AppUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<AppUserManager>();
            }
        }

    }
}

AzFace/Views/Shared/Editor.cshtml
@model AzFace.Models.EditorInputModel
<link href="@Url.Content("~/Content/jquery.Jcrop.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/jquery.Jcrop.js")" type="text/javascript"></script>

<div id="mainform">
    @using (Html.BeginForm("Edit", "Profile", FormMethod.Post))
    {
        @Html.DisplayFor(x => x.Profile.ImageUrl)         
        @Html.HiddenFor(x => x.Left)
        @Html.HiddenFor(x => x.Right)
        @Html.HiddenFor(x => x.Top)
        @Html.HiddenFor(x => x.Bottom)
        @Html.HiddenFor(x => x.Profile.ImageUrl)
        <input type='submit' name='action' value='Crop' />
    }
</div>

<script type="text/javascript">
    $(function () {
        jQuery('#profileImageEditor').Jcrop({
            onChange: showPreview,
            onSelect: showPreview,
            setSelect: [@Model.Top, @Model.Left, @Model.Right, @Model.Bottom],
            aspectRatio: 3/4
         });
   });


    function showPreview(coords)
    {
        if (parseInt(coords.w) > 0)
        {
            $('#Top').val(coords.y);
            $('#Left').val(coords.x);
            $('#Bottom').val(coords.y2);
            $('#Right').val(coords.x2);

            var width = @Model.Width;
              var height = @Model.Height;
             var rx = 100 / coords.w;
             var ry = 150 / coords.h;

             jQuery('#preview').css({
                 width: Math.round(rx * width) + 'px',
                 height: Math.round(ry * height) + 'px',
                 marginLeft: '-' + Math.round(rx * coords.x) + 'px',
                 marginTop: '-' + Math.round(ry * coords.y) + 'px'
             });
         }
     }
</script>

AzFace/Views/Shared/Header.cshtml
@{

    AjaxOptions ajaxOpts = new AjaxOptions
    {
        UpdateTargetId = "tableBody",
        HttpMethod = "Get",
        Url = Url.Action("GetPeopleDataJson"),
        OnSuccess = "processData",
        OnFailure = "processData2"
    };
}

<script>




    $(function () {
        // get handle to chat hub generated by SignalR     
        var chatHub = $.connection.chatHub;

        // add method that can be called by the hub to update chat     
        chatHub.client.publishHeaderMessage = function (senderPersonId, senderPersonName, receiverPersonId, text) {
            var chatWin = $("#messageIndicator");
            var line = "";
            line += "<tr class='messageData1'><td class='messageData'><a href='/Message/Index?personId=" + senderPersonId + "'>";
            line += "<div class='row'> <div class='col-sm-3'>";
            line += "<img width='50' height='50' src='/Home/GetImage?PersonId=" + senderPersonId + "'/>";
            line += "</div>";
            line += "<div class='col-sm-9'>";
            line += "<p>" + senderPersonName + "</p>";
            line += "<p style='overflow-wrap: break-word; width: 150px'>" + text + "</p>";
            line += "</div></div></a></td></tr>";

            chatWin.append(line);

            if (text != null) {
                var x = document.getElementById("myAudio");
                x.play();

                var count1 = parseInt($(".messageCount1").text());

                var count2 = 0;
                if (count1 == 0) {
                    count2 = count1 + 1;
                    $(".messageCount1").addClass("msgCount5");
                }
                else {
                    count2 = count1 + 1;
                }

                $(".messageCount1").text(count2);

            }




        };

        // start the connection with the hub     
        $.connection.hub.start();

    });



    function processData(data) {

        var currentPersonId = '@(Convert.ToInt32(Session["PersonId"]))';
        var target = $("#tableBody");
        target.empty();
        if (data.length > 0 && data.length < 8) {
            $(".dropdownMenuHeader").height(data.length * 75);
        }
        else if (data.length == 0) {
            $(".dropdownMenuHeader").height(60);
            target.append("<tr><td>Nothing found</td></tr>");
        }
        else if (data.length >= 9) {
            $(".dropdownMenuHeader").height(350);
        }
        for (var i = 0; i < data.length; i++) {
            var person = data[i];
            var line = "<tr>";
            line = line + "<td width='30%'>";
            line = line + "<a href='/Home/GetProfile/" + person.UserName + "'><img width='40' height='35' class='img-rounded' src='/Home/GetImage?PersonId=" + person.PersonId + "'/></a>";
            line = line + "</td><td width='40%'>";
            line = line + person.FirstName + "</td><td width='30%'>" + person.LastName;
            line = line + "</td><td style='display:none'>" + person.PersonId + "</td></tr>";
            target.append(line);
        }
    }

    $(document).ready(function () {
        $('#txtSearch').keyup(function (e) {
            if ($('#txtSearch').val().length == 1)
                $(".dropdown-toggle").dropdown("toggle");
            $("#searchForm").submit();
        });
    });

    $(document).ready(function () {
        $('#submitButton').click(function () {
            $(".dropdown-toggle").dropdown("toggle");
        });
    });


    $(document).ready(function () {
        $('#logout').popover({
            content: "<a href='/Account/Logout'>" + '@AzFace.Resource.LogOut' + "</a>",
            html: true,
            container: 'body',
            placement: 'bottom',
            trigger: 'focus'
        });
    });


    function processData3(data) {
        $(".dropdown-toggle").dropdown("toggle");
        var target = $("#tableBody");
        target.empty();
        target.append(data);
    }



    $(document).ready(function () {
        $('#requestes').popover({
            content: function () { return $('#requestHelp1').html() },
            html: true,
            //container: '#messageAndRequest',
            placement: 'bottom',
        });
    });


    $('html').on('mouseup', function (e) {
        if (!$(e.target).closest('.popover').length) {
            $('.popover').each(function () {
                $(this.previousSibling).popover('hide');
            });
        }
    });


    $(document).ready(function () {
        $('#messages').popover({
            "html": true,
            placement: 'bottom',
            "content": function () {
                return details_in_popup();
            }
        });

        function details_in_popup() {
            $.ajax({
                url: '/Message/GetLastAndNewMessages',
                success: function (response) {
                    $('#messages').data('bs.popover').options.content = response;
                    $('#messages').popover('show');
                },
                beforeSend: function () {
                    var loadingimage = '<div><img src="/Content/preloaders/Preloader_2.gif"></div>';
                    $('#messages').data('bs.popover').options.content = loadingimage;
                    $('#messages').popover('show');
                }

            });
        }
    });

</script>




<script>
    $(window).resize(function () {
        //$("body").prepend("<div>" + $(window).width() + "</div>");
        var width = $(window).width();
        if (width < 800) {
            $(".navbar-header").hide();
            $("#secondNavbar").show();
            $("#messageAndRequest").hide();
            $(".middle").hide();
            //$("#friendRequestIcon").hide();
            $("#friendRequestIcon").attr("class", "mobileClass");
            $("#secondNavbar").attr("class", "inline1");
            $("#inline2").attr("class", "inline1");
            $("#inline5").attr("class", "inline1");
            $("#optionsIcon1").show(100);

            $("#headerList").show(100);

            $("#friendsListDiv").hide();
        }
        else if (width > 800) {
            $("#secondNavbar").hide();
            $("#messageAndRequest").show();
            $(".middle").show();
            $("#friendRequestIcon").show();
        }
    });
</script>


<script>
    $("#glyphiconAlignJustify").click(function () {
        alert("hello");
    });

</script>

<nav class="navbar navbar-inverse navbar-fixed-top" id="movingNavbar">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-1">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/Home/Home">AzFace</a>
                    <audio id="myAudio">
                        <source src="~/Content/OutlookExpress.mp3" type="audio/mpeg">
                    </audio>
                </div>
            </div>

            <div class="col-sm-5" id="messageAndRequest">

                @if (User.Identity.IsAuthenticated)
                {
                    <div class="dropdown" id="findFriend">
                        @using (Ajax.BeginForm("GetPeopleDataJson", "Home", null, ajaxOpts, new { id = "searchForm" }))
                        {    
                            <div class="row">
                                <div class="col-sm-9 pull-center" id="forCenter">
                                    <div class="input-group">
                                        @Html.TextBox("searchTerm", null, new { id = "txtSearch", @class = "form-control", autocomplete = "off", data_toggle = "dropdown" })
                                        <span class="input-group-btn">
                                            <input class="form-control" id="submitButton" type="submit" value="@AzFace.Resource.Search" />
                                        </span>
                                    </div>
                                </div>

                                @if (ViewBag.RequestCount != 0)
                                {
                                    <div style="display: none">
                                        <div id="requestHelp1">
                                            <table class="table table-striped" id="requestHelp">
                                                <tbody>

                                                    @foreach (var request in ViewBag.FriendRequestes)
                                                    {
                                                        int str = request.FriendId;
                                                        <tr>
                                                            <td style="color: blue;">@request.FirstName</td>
                                                            <td style="color: blue;">@request.LastName</td>
                                                            <td style="color: blue;">@Html.ActionLink("Confirm", "ConfirmFriendship", new { str })</td>
                                                        </tr> 
                                                    }
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                }

                            </div>
                                                  
                        }
                        <input type="text" class="dropdown-toggle" data-toggle="dropdown" style="display: none;">
                        <div class="dropdown-menu dropdownMenuHeader">
                            <table class="table table-striped" border="0">
                                <tbody id="tableBody">
                                </tbody>
                            </table>
                        </div>
                    </div>
                }
            </div>
            @if (User.Identity.IsAuthenticated)
            {
                <div class="col-sm-2 middle">
                    <div class="navbar-header">

                        <img width="30" height="30" class="img-rounded"  src="@Url.Action("GetImage", "Home", new { PersonId = Convert.ToInt32(Session["PersonId"]) })" />
                        <ul class="nav navbar-nav">
                            <li><a href="/Home/Index">@ViewBag.PersonName</a></li>
                            <li>@Html.ActionLink("Home", "Home", "Home")</li>
                        </ul>

                    </div>
                </div>

                <div class="col-sm-3" id="friendRequestIcon">
                    <div class="row">
                        <div id="secondNavbar" class="hide">
                            <div class="navbar-header">
                                <a class="navbar-brand" href="/Home/Home">AzFace</a>
                                <audio id="myAudio1">
                                    <source src="~/Content/OutlookExpress.mp3" type="audio/mpeg">
                                </audio>
                            </div>
                        </div>

                        <div id="inline2" class="col-sm-3">
                            @if (ViewBag.RequestCount != 0)
                            {                 
                                <p style="color: red" class="requestCount1">@ViewBag.RequestCount</p>
                            }
                            else
                            {                 
                                <p class="requestCount1">0</p>
                            }
                            <img width="25" height="25" id="requestes" src="~/Content/ffr.jpg" />
                        </div>

                        <div id="inline5" class="col-sm-9">
                            @if (ViewBag.MessageCount != 0)
                            {                 
                                <p style="color: red" class="messageCount1">@ViewBag.MessageCount</p>
                            }
                            else
                            {                 
                                <p class="messageCount1">0</p>
                            }
                            <img width="25" height="25" id="messages" src="~/Content/msgIcon.jpg" />
                        </div>
                        <div id="headerList" class="inline1" style="display: none">
                            <p id="glyphiconAlignJustify" style="color: white">menu<span class="glyphicon glyphicon-align-justify"></span></p>
                        </div>
                    </div>

                </div>
                <div class="col-sm-1 middle">
                    <button type="button" class="btn btn-default btn-sm pull-right " id="logout">
                        <span class="glyphicon glyphicon-cog"></span>
                    </button>
                </div>
            }

        </div>
    </div>
</nav>

AzFace/Views/Shared/LinkExpired.cshtml
@{
    ViewBag.Title = "LinkExpired";
}

<h2>LinkExpired</h2>


<p>This link is expired, try sending another link to your email</p>

AzFace/Views/Shared/PasswordNotReset.cshtml
@{
    ViewBag.Title = "PasswordNotReset";
}
<br>

<h2>PasswordNotReset</h2>

<p>Password should contain at least 6 character, at least 1 uppercase letter and at least 1 numeric </p>

AzFace/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.11.3.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>
    <script src="~/Scripts/bootstrap.min.js" type="text/javascript"></script>

    <link href="~/Content/MySite.css" rel="stylesheet" />
     <link href="~/Content/jquery-ui.css" rel="stylesheet" />

   @* <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />*@
    <script src="~/Scripts/jquery.timeago.js"></script>

    <script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
    <script type="text/javascript" src="/signalr/hubs"></script>

    <script src="~/Scripts/autosize.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery-ui.js" type="text/javascript"></script>


    <script src="~/Scripts/jquery.fileupload.js" type="text/javascript"></script>
    <link href="~/Content/jquery.fileupload.css" rel="stylesheet" />


    <script src="~/Scripts/enscroll-0.6.1.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.dialogextend.js" type="text/javascript"></script>

</head>
<body class="container">
    <div class="container">
        @Html.Partial("Header")
        @RenderBody()
        @if (IsSectionDefined("scripts"))
        {
            @RenderSection("scripts")
        }
    </div>
</body>

<script>
    autosize(document.querySelectorAll('textarea'));
</script>

<script type="text/javascript">
    var idleTime = 0;
    $(document).ready(function () {
        //Increment the idle time counter every minute.
        var idleInterval = setInterval(timerIncrement, 60000); // 1 minute

        //Zero the idle timer on mouse movement.
        $(this).mousemove(function (e) {
            idleTime = 0;
        });
        $(this).keypress(function (e) {
            idleTime = 0;
        });
    });

    function timerIncrement() {
        idleTime = idleTime + 1;
        if (idleTime > 10) { // 11 minutes
            window.location.reload();
        }
    }
</script>

</html>