AzFace/Models/Connection/Album.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzFace.Models.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public Album()
        {
            this.Photos = new HashSet<Photo>();
        }
    
        public int AlbumId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
    }
}

AzFace/Controllers/AlbumController.cs
using AzFace.Infrastructure;
using AzFace.Models;
using AzFace.Models.Connection;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace AzFace.Controllers
{

    public class JSonAlbum
    {

        public int AlbumId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string Name { get; set; }
        public string CreationTime { get; set; }
        public List<int> PhotoIds { get; set; }
    }

    public class AlbumController : Controller
    {

        public ActionResult Index()
        {

            int currentPersonId = Convert.ToInt32(Session["PersonId"]);
            ViewBag.FriendRequestes = FriendHelper.GetFriendRequestes(currentPersonId);
            ViewBag.RequestCount = FriendHelper.GetFriendRequestCount(currentPersonId);
            ViewBag.Messages = FriendHelper.GetMessages(currentPersonId);
            ViewBag.MessageCount = FriendHelper.GetMessageCount(currentPersonId);

            using (EFPersonRepository db = new EFPersonRepository())
            {
                List<Album> albums = db.Albums.Where(x => x.PersonId == currentPersonId).ToList();
                return View(albums);
            }
        }



        [HttpPost]
        public JsonResult AsyncUpload(IEnumerable<HttpPostedFileBase> files, string albumName)
        {
            int count = 0;
            int currentPersonId = Convert.ToInt32(Session["PersonId"]);
            Album album1 = null;
            if (files != null)
            {

                using (EFPersonRepository db = new EFPersonRepository())
                {
                    Album album = new Album { CreationTime = DateTime.Now, PersonId = currentPersonId, Name = albumName };
                    db.context.Albums.Add(album);
                    db.context.SaveChanges();
                }
                foreach (var file in files)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        using (EFPersonRepository db = new EFPersonRepository())
                        {

                            Photo photo = new Photo { ImageMimeType = file.ContentType, Image = new byte[file.ContentLength], PersonId = currentPersonId };
                            file.InputStream.Read(photo.Image, 0, file.ContentLength);

                            album1 = db.Albums.OrderByDescending(x => x.AlbumId).FirstOrDefault(x => x.PersonId == currentPersonId);
                            album1.Photos.Add(photo);
                            //db.context.SaveChanges();

                            Item item = new Item
                            {
                                ImageMimeType = file.ContentType,
                                ImageData = photo.Image,
                                PersonId = currentPersonId,
                                InitialPersonId = currentPersonId,
                                LikeNumber = 0,
                                ShareOption = "OnlyMe",
                                Text = albumName,
                                SharedTime = DateTime.Now
                            };
                            item.Photos.Add(photo);
                            Share share = new Share
                            {
                                ItemId = item.ItemId,
                                PersonId = currentPersonId
                            };
                            db.context.Shares.Add(share);
                            db.SaveItem(item);

                        }
                    }
                }

                using (EFPersonRepository db = new EFPersonRepository())
                {
                    Album album2 = db.Albums.FirstOrDefault(x => x.AlbumId == album1.AlbumId);

                    List<int> photoIds = new List<int>();
                    foreach (Photo photo2 in album2.Photos)
                    {
                        photoIds.Add(photo2.PhotoId);
                    }

                    JSonAlbum jsonAlbum = new JSonAlbum
                    {
                        AlbumId = album2.AlbumId,
                        CreationTime = album2.CreationTime.ToString(),
                        Name = album2.Name,
                        PersonId = album2.PersonId,
                        PhotoIds = photoIds
                    };

                    return Json(jsonAlbum, JsonRequestBehavior.AllowGet);
                }

            }
            return new JsonResult { Data = "Successfully " + count + " file(s) uploaded" };
        }


        [HttpPost]
        public JsonResult GetCarouselItems(int photoId, int albumId, string direction)
        {
            int currentPersonId = Convert.ToInt32(Session["PersonId"]);
            if (albumId == 0 || photoId == 0)
                return null;

            using (EFPersonRepository db = new EFPersonRepository())
            {
                List<Photo> photos = db.Photos.Where(x => x.PhotoId >= photoId && x.AlbumId == albumId && x.PersonId == currentPersonId && x.ImageMimeType != null).ToList();

                if (direction == "left")
                    photos = db.Photos.Where(x => x.PhotoId < photoId && x.AlbumId == albumId && x.PersonId == currentPersonId && x.ImageMimeType != null).ToList();
                Photo photo = null;
                int? nextPhotoId = 0;

                if (photos.Count() > 0)
                    photo = photos[0];
                if (photos.Count() > 1)
                {
                    nextPhotoId = photos[1].PhotoId;
                }




                var carouselItem = new
                {
                    PersonId = photo.PersonId,
                    ImgMimeType = photo.ImageMimeType,
                    PersonName = photo.Person.FirstName + " " + photo.Person.LastName,
                    AlbumId = photo.AlbumId,
                    Text = photo.Item.Text,
                    Comments = photo.Item.Comments.Select(x => new { 
                        PersonId = x.PersonId, 
                        CommentTime = x.CommentTime.Value.ToShortDateString(), 
                        Text = x.Text, 
                        FirstName = x.Person.FirstName, 
                        LastName = x.Person.LastName }),

                    LikeNumber = photo.Item.LikeNumber,
                    InitialPersonId = photo.Item.InitialPersonId,
                    InitialPersonName = photo.Item.Person1.FirstName + " " + photo.Item.Person1.LastName,
                    SharedTime = photo.Item.SharedTime.ToString(),
                    ShareOption = photo.Item.ShareOption,
                    VideoPath = photo.Item.VideoPath,
                    NextPhotoId = nextPhotoId,
                    PhotoId = photo.PhotoId,
                    ItemId = photo.ItemId
                };
                return Json(carouselItem, JsonRequestBehavior.AllowGet);
            }
        }


        [HttpGet]
        public FileContentResult GetPhoto(int photoId)
        {
            using (EFPersonRepository db = new EFPersonRepository())
            {
                int currentPersonId = Convert.ToInt32(Session["PersonId"]);

                Photo photo = db.Photos.FirstOrDefault(x => x.PhotoId == photoId && x.PersonId == currentPersonId);
                if (photo != null && photo.Image != null)
                {
                    return File(photo.Image, photo.ImageMimeType);
                }
                else
                {
                    return null;
                }
            }
        }

        public ActionResult GetAlbum(int albumId)
        {

            int currentPersonId = Convert.ToInt32(Session["PersonId"]);
            ViewBag.FriendRequestes = FriendHelper.GetFriendRequestes(currentPersonId);
            ViewBag.RequestCount = FriendHelper.GetFriendRequestCount(currentPersonId);
            ViewBag.Messages = FriendHelper.GetMessages(currentPersonId);
            ViewBag.MessageCount = FriendHelper.GetMessageCount(currentPersonId);

            using (EFPersonRepository db = new EFPersonRepository())
            {
                Album album = db.Albums.FirstOrDefault(x => x.AlbumId == albumId);
                return View(album);
            }
        }

        public JsonResult GetPeopleDataJson(String searchTerm)
        {
            using (EFPersonRepository db = new EFPersonRepository())
            {
                if (!String.IsNullOrWhiteSpace(searchTerm))
                {
                    int personId = Convert.ToInt32(Session["PersonId"]);
                    List<Person> people = db.People.Where(x => x.FirstName.StartsWith(searchTerm) || x.LastName.StartsWith(searchTerm)).ToList();
                    List<Person> people1 = people.Where(x => x.PersonId != personId).Select(p =>
                        new Person { PersonId = p.PersonId, LastName = p.LastName, FirstName = p.FirstName }).ToList();

                    return Json(people1, JsonRequestBehavior.AllowGet);
                }
                else
                    return null;
            }
        }

        public JsonResult GetAjaxImage(int albumId)
        {
            using (EFPersonRepository db = new EFPersonRepository())
            {
                int currentPersonId = Convert.ToInt32(Session["PersonId"]);
                Random r = new Random();

                Album album = db.Albums.FirstOrDefault(x => x.AlbumId == albumId && x.PersonId == currentPersonId);
                int index = r.Next(0, album.Photos.Count() - 1);
                Photo photo = album.Photos.ElementAtOrDefault(index);
                // hemin albomu tapir, sonra albomun sekillerinin arasinda random sekil goturur. sonra hemin sekilin id  sin qaytarir

                return Json(new { PhotoId = photo.PhotoId }, JsonRequestBehavior.AllowGet);
            }
        }




    }
}

AzFace/Views/Album/GetAlbum.cshtml
@model AzFace.Models.Connection.Album

@{
    ViewBag.Title = "GetAlbum";
}

<br>
<div class="row">
    @foreach (AzFace.Models.Connection.Photo photo in Model.Photos)
    {
        <div class='col-sm-3'>
            <img width="250" height="200" src="/Album/GetPhoto?photoId=@photo.PhotoId"/>
        </div>
    }
</div>

AzFace/Views/Album/Index.cshtml
@model List<AzFace.Models.Connection.Album>



<script src="~/Scripts/jquery.form.js"></script>
<script>
    (function () {
        var bar = $('.progress-bar');
        var percent = $('.progress-bar');
        var status = $('#status');

        $('form').ajaxForm({
            beforeSend: function () {
                status.empty();
                var percentValue = '0%';
                bar.width(percentValue);
                percent.html(percentValue);
            },
            uploadProgress: function (event, position, total, percentComplete) {
                var percentValue = percentComplete + '%';
                bar.width(percentValue);
                percent.html(percentValue);
            },
            success: function (d) {
                var percentValue = '100%';
                bar.width(percentValue);
                percent.html(percentValue);
                $('#fu1').val('');
                //alert(d);
            },
            complete: function (xhr) {
                status.html(xhr.responseText);
            }
        });
    })();
</script>

<script>

    //qalani da javascriptlikdi.
    var theTimer;

    $(document).on("mouseover", ".albumImg", function () {
        var albumId = $(this).attr('id');
        getNextImage(albumId);

        $(this).mouseout(function () {
            clearTimeout(theTimer);
        });
    });




    function getNextImage(albumId) { // o da burdadi.
        theTimer = setTimeout(function () { // gozlemeni setTimeout funksiyasi eliyir.

            var album = { albumId: albumId }
            $.ajax({
                url: '/Album/GetAjaxImage', // bu da gedir GetAjaxImage metodun cagirir
                type: 'POST',
                data: JSON.stringify(album),
                contentType: 'application/json; charset=utf-8',
                beforeSend: function () {
                    $("." + albumId).fadeTo(300, 0.1);
                },
                success: function (data) { // bura, burdan sekili tapir ve src  attributun deyisir, yeni sekile 
                    var target = $("#" + albumId);
                    target.attr("src", "/Album/GetPhoto?photoId=" + data.PhotoId);
                },
                error: function (data) {
                    //alert(data);
                },
                complete: function () { // ne qeder ki, mouse sekilin ustundedi
                    getNextImage(albumId) // getNextImage yeniden cagirir. burda loop duzeldir. bu loop u qirmaq ucun. mouse leave eventiden istifade eliyirem
                    $("." + albumId).fadeTo(500, 1);
                }
            });

        }, 2500); // sonra 2.5 saniye gozleyir.
    }

</script>


<script>
    $(document).on("mouseover", ".galleryImageClass", function () {

        var options = $(this).children(".galleryOptions");
        options.animate({ bottom: '10px' });
        options.show();

        $(this).mouseout(function () {
            options.hide();
        });
    });


    function processCarouselItems(data) {
        var target = $("#carouselId");
        target.empty();
        var line = "";
        var line1 = "";

        if (data != undefined) {

            line = line + "<div id='carouselItemId' class='item active picture-container'>";
            line = line + "<img id='picture' class='img-responsive' src='/Album/GetPhoto?photoId=" + data.PhotoId + "'/>";
            line = line + "</div>"

            target.append(line);



            $("#carouselCommentDiv").empty();

            var ItemId = data.ItemId;
            var Origin = "carousel";

            var values = { id: ItemId, origin: Origin }
            $.ajax({
                url: "/PartialComment/Index",
                type: 'POST',
                data: JSON.stringify(values),
                contentType: 'application/json; charset=utf-8',
                success: function (data) {
                    $("#carouselCommentDiv").append(data);
                },
                error: function (data) {
                    alert("hello error");
                }

            });


            if (data.NextPhotoId != 0) {
                line1 = "/Album/GetCarouselItems?photoId=" + data.NextPhotoId + "&albumId=" + data.AlbumId + "&direction=right";
            }
            else {
                line1 = "/Album/GetCarouselItems?photoId=" + data.NextPhotoId + "&albumId=" + data.AlbumId + "&direction=right";
            }

            $("#rightButtonId").attr("href", line1);
            $("#leftButtonId").attr("href", "/Album/GetCarouselItems?photoId=" + data.PhotoId + "&albumId=" + data.AlbumId + "&direction=left");

            $("#myModal1").modal();


        }



    }

</script>



<br>
<br>
<div class="row">
    <div class="col-sm-4">
        <button class="btn btn-info" data-toggle="modal" data-target="#myModal">CreateAlbum</button>
    </div>
</div>

<div class="row albumsDiv">
    @foreach (AzFace.Models.Connection.Album album in Model) // sonra loop dan albomlarin birinci sekilin yukleyirem
    {
        <div class='col-sm-3 galleryImageClass'>
            <div class="galleryOptions" style="display: none">
                <div class="col-sm-6">
                    <button class="btn btn-info">add image</button>
                </div>
                <div class="col-sm-6">
                    <button class="btn btn-info">remove</button>
                </div>
            </div>
            <p>@album.Photos.Count() photos</p>
            <div class="@album.AlbumId mainAlbum">
                <a data-ajax='true' data-ajax-loading='#progress' data-ajax-method='POST' data-ajax-success='processCarouselItems' href='/Album/GetCarouselItems?photoId=@album.Photos.FirstOrDefault().PhotoId&albumId=@album.AlbumId'>
                    <img class="albumImg" id="@album.AlbumId" width="250" height="200" src="/Album/GetPhoto?photoId=@album.Photos.FirstOrDefault().PhotoId"/>
                </a>
            </div>

            <div>@album.Name</div>
        </div>
    }
</div>







<!-- Modal -->
<div class="modal modal-wide " id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
                @*start*@


                @using (Ajax.BeginForm("AsyncUpload", "Album", new AjaxOptions() { HttpMethod = "POST" }, new { enctype = "multipart/form-data", id = "multiFileForm" }))
                {
                    @Html.AntiForgeryToken()
                    <input type="file" name="files" id="fu1" multiple="multiple" />
                    <input name="albumName" type="text" />
                    <input type="submit" value="Upload File" />
  
                }

                <div class="progress">
                    <div class="progress-bar">0%</div>
                </div>
                <div id="status"></div>

                @section scripts{
                    <script src="~/Scripts/jquery.form.js"></script>
                    <script>
                        (function () {
                            var bar = $('.progress-bar');
                            var percent = $('.progress-bar');
                            var status = $('#status');

                            $('#multiFileForm').ajaxForm({
                                beforeSend: function () {
                                    status.empty();
                                    var percentValue = '0%';
                                    bar.width(percentValue);
                                    percent.html(percentValue);
                                },
                                uploadProgress: function (event, position, total, percentComplete) {
                                    var percentValue = percentComplete + '%';
                                    bar.width(percentValue);
                                    percent.html(percentValue);
                                },
                                success: function (data) {
                                    var percentValue = '100%';
                                    bar.width(percentValue);
                                    percent.html(percentValue);

                                    var target = $('.albumsDiv');
                                    var line = "<div class='col-sm-3 profilePopupClass'>";
                                    line += "<p>" + data.PhotoIds.length + " photos</p>";
                                    line += "<p class='" + data.AlbumId + "'>";
                                    line += '<img class="albumImg" id="' + data.AlbumId + '" width="250" height="200" src="/Album/GetPhoto?photoId=' + data.PhotoIds[0] + '"/>';
                                    line += "</p>";
                                    line += '<div class="galleryBottom">' + data.Name + '</div>';
                                    line += "</div>";

                                    target.append(line);
                                },
                                complete: function (xhr) {
                                    status.html(xhr.responseText);
                                }
                            });
                        })();
                    </script>
                }


                @*end*@
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="myModal1" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body" id="modalId">

                <div class="row">
                    <div class="col-sm-8">

                        <div id="myCarousel" class="carousel" data-ride="carousel" data-interval="false">
                            <!-- Wrapper for slides -->
                            <div class="carousel-inner" role="listbox" id="carouselId">
                                <div class="item active">
                                    <img width="460" height="345" src="@Url.Action("GetImage", "Home", new { personId = 1 })">
                                </div>
                            </div>

                            <!-- Left and right controls-->
                            <a class="left carousel-control" id="leftButtonId" role="button" data-ajax="true" data-ajax-loading="#progress" data-ajax-method="POST" data-ajax-success="processCarouselItems" href="#">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" id="rightButtonId" role="button" data-ajax="true" data-ajax-loading="#progress" data-ajax-method="POST" data-ajax-success="processCarouselItems" href="#">

                                @* <a class="right carousel-control" id="rightId" href="#myCarousel" role="button" data-slide="next">*@
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>

                    </div>

                    <div class="col-sm-3" id="carouselCommentDiv">
                    </div>
                </div>
            </div>



        </div>

    </div>
</div>