AzFace/Controllers/MessageController.cs
using AzFace.Infrastructure;
using AzFace.Models;
using AzFace.Models.Connection;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace AzFace.Controllers
{

    public class MessageTest
    {
        public string Text;
        public string MessageTime;
        public string FirstName;
        public string LastName;
        public int? PersonId;
    }

    [Authorize]
    public class MessageController : Controller
    {

        public ActionResult Index(MessageViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Home", "Home", null);
            }

            int PersonId = model.PersonId;
            int currentPersonId = Convert.ToInt32(Session["PersonId"]);
            ViewBag.FriendRequestes = FriendHelper.GetFriendRequestes(currentPersonId);
            ViewBag.RequestCount = FriendHelper.GetFriendRequestCount(currentPersonId);
            ViewBag.Messages = FriendHelper.GetMessages(currentPersonId);
            ViewBag.MessageCount = FriendHelper.GetMessageCount(currentPersonId);

            using (EFPersonRepository db = new EFPersonRepository())
            {
                Person senderPerson = db.People.FirstOrDefault(x => x.PersonId == PersonId);
                Person receiverPerson = db.People.FirstOrDefault(x => x.PersonId == currentPersonId);

                if (senderPerson == null)
                {
                    return RedirectToAction("Home","Home", null);
                }

                String senderName = senderPerson.FirstName + " " + senderPerson.LastName;
                String receiverName = receiverPerson.FirstName + " " + receiverPerson.LastName;

                List<Message> newMessages = db.Messages.Where(x =>
                    x.MessageFrom == PersonId && x.MessageTo == currentPersonId ||
                    x.MessageTo == PersonId && x.MessageFrom == currentPersonId
                    ).OrderBy(n => n.MessageTime).ToList();
                for (int i = 0; i < newMessages.Count(); i++)
                {
                    Message message = newMessages[i];
                    message.ReadTimes = message.ReadTimes + 1;
                }
                db.context.SaveChanges();

                MessageHelper messageHelper = new MessageHelper
                {
                    Messages = newMessages,
                    Sender = new Person
                    {
                        PersonId = PersonId,
                        FirstName = senderPerson.FirstName,
                        LastName = senderPerson.LastName
                    },
                    Receiver = new Person
                    {
                        PersonId = currentPersonId,
                        FirstName = receiverPerson.FirstName,
                        LastName = receiverPerson.LastName
                    }
                };
                return View(messageHelper);
            }
        }


        public JsonResult Messages(int personId)
        {
            int currentPersonId = Convert.ToInt32(Session["PersonId"]);
            ViewBag.FriendRequestes = FriendHelper.GetFriendRequestes(currentPersonId);
            ViewBag.RequestCount = FriendHelper.GetFriendRequestCount(currentPersonId);
            ViewBag.Messages = FriendHelper.GetMessages(currentPersonId);
            ViewBag.MessageCount = FriendHelper.GetMessageCount(currentPersonId);

            using (EFPersonRepository db = new EFPersonRepository())
            {
                Person senderPerson = db.People.FirstOrDefault(x => x.PersonId == personId);
                Person receiverPerson = db.People.FirstOrDefault(x => x.PersonId == currentPersonId);

                String senderName = senderPerson.FirstName + " " + senderPerson.LastName;
                String receiverName = receiverPerson.FirstName + " " + receiverPerson.LastName;

                List<Message> newMessages = db.Messages.Where(x =>
                    x.MessageFrom == personId && x.MessageTo == currentPersonId ||
                    x.MessageTo == personId && x.MessageFrom == currentPersonId
                    ).OrderBy(n => n.MessageTime).ToList();
                for (int i = 0; i < newMessages.Count(); i++)
                {
                    Message message = newMessages[i];
                    message.ReadTimes = message.ReadTimes + 1;
                }
                db.context.SaveChanges();

                List<Message> jsonMessages = newMessages.Select(x => new Message
                {
                    MessageFrom = x.MessageFrom,
                    MessageTo = x.MessageTo,
                    MessageId = x.MessageId,
                    MessageTime = x.MessageTime,
                    Text = x.Text,
                    ReadTimes = x.ReadTimes,
                    Delivered = x.Delivered
                }).ToList();

                MessageHelper messageHelper = new MessageHelper
                {
                    Messages = jsonMessages,
                    Sender = new Person
                    {
                        PersonId = personId,
                        FirstName = senderPerson.FirstName,
                        LastName = senderPerson.LastName
                    },
                    Receiver = new Person
                    {
                        PersonId = currentPersonId,
                        FirstName = receiverPerson.FirstName,
                        LastName = receiverPerson.LastName
                    }
                };
                return Json(messageHelper, JsonRequestBehavior.AllowGet);
            }
        }



        public PartialViewResult PartialMessages(int personId)
        {
            int currentPersonId = Convert.ToInt32(Session["PersonId"]);
            ViewBag.FriendRequestes = FriendHelper.GetFriendRequestes(currentPersonId);
            ViewBag.RequestCount = FriendHelper.GetFriendRequestCount(currentPersonId);
            ViewBag.Messages = FriendHelper.GetMessages(currentPersonId);
            ViewBag.MessageCount = FriendHelper.GetMessageCount(currentPersonId);

            using (EFPersonRepository db = new EFPersonRepository())
            {
                Person senderPerson = db.People.FirstOrDefault(x => x.PersonId == personId);
                Person receiverPerson = db.People.FirstOrDefault(x => x.PersonId == currentPersonId);

                String senderName = senderPerson.FirstName + " " + senderPerson.LastName;
                String receiverName = receiverPerson.FirstName + " " + receiverPerson.LastName;

                List<Message> newMessages = db.Messages.Where(x =>
                    x.MessageFrom == personId && x.MessageTo == currentPersonId ||
                    x.MessageTo == personId && x.MessageFrom == currentPersonId
                    ).OrderBy(n => n.MessageTime).ToList();
                for (int i = 0; i < newMessages.Count(); i++)
                {
                    Message message = newMessages[i];
                    message.ReadTimes = message.ReadTimes + 1;
                }
                db.context.SaveChanges();

                List<Message> jsonMessages = newMessages.Select(x => new Message
                {
                    MessageFrom = x.MessageFrom,
                    MessageTo = x.MessageTo,
                    MessageId = x.MessageId,
                    MessageTime = x.MessageTime,
                    Text = x.Text,
                    ReadTimes = x.ReadTimes,
                    TimeStamp = x.TimeStamp,
                    Delivered = x.Delivered,
                    FileName = x.FileName
                }).ToList();

                MessageHelper messageHelper = new MessageHelper
                {
                    Messages = jsonMessages,
                    Sender = new Person
                    {
                        PersonId = personId,
                        FirstName = senderPerson.FirstName,
                        LastName = senderPerson.LastName
                    },
                    Receiver = new Person
                    {
                        PersonId = currentPersonId,
                        FirstName = receiverPerson.FirstName,
                        LastName = receiverPerson.LastName
                    }
                };
                return PartialView(messageHelper);
            }
        }














        public JsonResult GetPeopleDataJson(String searchTerm)
        {
            using (EFPersonRepository db = new EFPersonRepository())
            {
                if (!String.IsNullOrWhiteSpace(searchTerm))
                {
                    int personId = Convert.ToInt32(Session["PersonId"]);
                    List<Person> people = db.People.Where(x => x.FirstName.StartsWith(searchTerm) || x.LastName.StartsWith(searchTerm)).ToList();
                    List<Person> people1 = people.Where(x => x.PersonId != personId).Select(p =>
                        new Person { PersonId = p.PersonId, LastName = p.LastName, FirstName = p.FirstName }).ToList();

                    return Json(people1, JsonRequestBehavior.AllowGet);
                }
                else
                    return null;
            }
        }

        [HttpPost]
        public JsonResult SetPeopleMessageJson(String messageReply, int receiverPersonId)
        {
            using (EFPersonRepository db = new EFPersonRepository())
            {
                if (!String.IsNullOrWhiteSpace(messageReply) && receiverPersonId != 0)
                {
                    int senderPersonId = Convert.ToInt32(Session["PersonId"]);
                    Message message = new Message
                    {
                        MessageFrom = senderPersonId,
                        MessageTo = receiverPersonId,
                        MessageTime = DateTime.Now,
                        Text = messageReply,

AzFace/Views/Home/GetFriends.cshtml
@model List<AzFace.Models.Connection.Person>

@{
    ViewBag.Title = "GetFriends";
}


<br>
<br>
<h2>Friends</h2>


<div class="row">
    @foreach (AzFace.Models.Connection.Person person in Model)
    {
        <div class="col-sm-2">
            <img width="145" height="130" class="img-rounded" src="@Url.Action("GetImage", "Home", new { person.PersonId })" />
            <br>
            @person.FirstName @person.LastName
        </div>
    }
</div>

AzFace/Views/Home/GetProfile.cshtml
@model AzFace.Models.Connection.Person

@{
    ViewBag.Title = "Index";

}

<script>
    $(document).ready(function () {
        $('#photoChange').popover({
            content: function () { return $('#uploader').html() },
            html: true, placement: 'bottom'
        });
    });

    $(document).on('click', '#fileUpload', function (e) {
        e.preventDefault();
        $('#uploader').submit();
    });

</script>


<script type="text/javascript">

    function processData2(request, error) {
        alert("This is the OnFailure Callback:" + error);
    }

    function processSharedData(data) {
        var target = $("#sharedItem");
        target.append(data);
    }







    function processCommentsData(data) {
        $("#" + data.ItemId).append("<p>" + data.ItemComment + "</p>");
        $("#textArea" + data.ItemId).val("");
    }

    function processComments(data) {
        var target = $("#" + data.ItemId);
        target.empty();
        var line = "<table><tbody>";
        for (var j = 0; j < data.Comments.length; j++) {
            var comment = data.Comments[j];
            line = line + "<tr><td>";
            line = line + "<img width='25' height='25' src='/Home/GetImage?PersonId=" + comment.PersonId + "'/>";
            line = line + "</td><td>";
            line = line + comment.FirstName + " " + comment.LastName + ": &nbsp " + "</td><td>";
            line = line + comment.Text + "</td></tr>";
        }
        line = line + "</tbody></table>"
        target.append(line);
    }




</script>



<script>

    $(document).ready(function () {
        $('#friendRequest').click(function () {
            var PersonId = '@Model.PersonId';
            var number1 = { PersonId: PersonId }
            $.ajax({
                url: '/Home/AddFriend',
                type: 'POST',
                data: JSON.stringify(number1),
                contentType: 'application/json; charset=utf-8',
                success: function (data) {
                    $("#friendRequest").text(data);
                },
                error: function (data) {
                    alert(data);
                }
            });



        });
     });

    document.addEventListener('scroll', function (event) {

        var page = $(".intro").val();
        if (document.body.scrollHeight <= document.body.scrollTop + window.innerHeight) {
            var pageValue = parseInt(page);
            pageValue = pageValue + 1;
            $(".intro").val(pageValue);
            callFunction1();
        }

        else if (document.body.scrollTop > 150) {
            //$("#movingNavbar").hide(100);
            //$("#optionsIcon1").show(100);

        }

        else if (document.body.scrollTop < 150) {
            //$("#movingNavbar").show(100);
            //$("#optionsIcon1").hide(100);
        }
    });


    $(document).ready(callFunction());

    function callFunction() {
        var page = $(".intro").val();
        var pageValue = parseInt(page);
        pageValue = pageValue + 1;
        $(".intro").val(pageValue);
        var number1 = { PersonId: '@Model.PersonId' }
        $.ajax({
            url: '/Home/GetFriendProfile1',
            type: 'POST',
            data: JSON.stringify(number1),
            contentType: 'application/json; charset=utf-8',
            success: function (data) {
                var target = $("#sharedItem");
                var line = "";
                for (var i = 0; i < data.length; i++) {
                    var item = data[i];
                    line = line + "<tr><td>";
                    line = line + "<div class='sharedItemDiv'>";
                    line = line + "<div class='sharedItemHeaderDiv'>";
                    line = line + "<img width='50' height='50' src='/Home/GetImage?PersonId=" + item.PersonId + "'/>";
                    line = line + "<p>" + item.PersonName + "</p>";
                    line = line + "<p>" + item.Text + "</p>";
                    line = line + "<div>";
                    if (item.ImgMimeType != undefined) {
                        line = line + "<img class='img-responsive' src='/Home/GetSharedImage?ItemId=" + item.ItemId + "'/>";
                    }

                    line = line + "<form class ='form-inline' action='/' data-ajax='true' data-ajax-failure='processData2' data-ajax-method='Get' data-ajax-mode='replace' data-ajax-success='processCommentsData' data-ajax-update='#tableBody' data-ajax-url='/Home/AddCommentToItem' method='post'>";
                    line = line + "<textarea class='form-control' id='textArea" + item.ItemId + "' name='comment' cols='50' rows='1' placeholder='add comment'></textarea>";
                    line = line + "<input type='hidden' name='itemId' value=" + item.ItemId + ">";
                    line = line + "<input class='submitCommentButton' type='submit' value='submit'>";
                    line = line + "</form>";

                    for (var j = 0; j < item.Comments.length; j++) {
                        var comment = item.Comments[j];
                        line = line + "<p>" + comment + "</p>";
                    }
                    line = line + "<div id='" + item.ItemId + "'></div>";
                    line = line + "</div></td></tr><tr><td><br><br></td></tr>";
                }
                target.append(line);
            },
            error: function (data) {
                alert(data);
            }
        });
    }



    function callFunction1() {
        var pageNumber = $(".intro").val();
        var number1 = { Page: pageNumber, PersonId: '@Model.PersonId' }
        $.ajax({
            url: '/Home/GetFriendProfile',
            type: 'POST',
            data: JSON.stringify(number1),
            contentType: 'application/json; charset=utf-8',
            success: function (data) {
                var target = $("#sharedItem");
                var line = "";
                for (var i = 0; i < data.length; i++) {
                    var item = data[i];
                    line = line + "<tr><td>";
                    line = line + "<div class='sharedItemDiv'>";
                    line = line + "<div class='sharedItemHeaderDiv'>";
                    line = line + "<p><img width='50' height='50' src='/Home/GetImage?PersonId=" + item.PersonId2 + "'/>" + item.PersonId + "</p>";
                    line = line + "<p>" + item.Text + "</p>";
                    line = line + "<div>";
                    if (item.ImgMimeType != undefined) {
                        line = line + "<img class='img-responsive' src='/Home/GetSharedImage?ItemId=" + item.ItemId + "'/>";
                    }
                    line = line + "<div class='row'>";

                    line = line + "<div class='col-sm-2'>";
                    line = line + "<a href='#'>Like</a>";
                    line = line + "</div>";
                    line = line + "<div class='col-sm-3'>";
                    line = line + "<a data-ajax='true' data-ajax-loading='#progress' data-ajax-method='POST' data-ajax-success='processComments' href='/Home/GetCommentsFromItem?itemId=" + item.ItemId + "'>" + item.Comments.length + "&nbsp Comments</a>";
                    line = line + "</div>";
                    line = line + "<div class='col-sm-2'>";
                    line = line + "<a href='#'>Share</a>";
                    line = line + "</div>";

                    line = line + "</div>";
                    line = line + "<form class ='form-inline' action='/' data-ajax='true' data-ajax-failure='processData2' data-ajax-method='Get' data-ajax-mode='replace' data-ajax-success='processCommentsData' data-ajax-update='#tableBody' data-ajax-url='/Home/AddCommentToItem' method='post'>";
                    line = line + "<textarea class='form-control' id='textArea" + item.ItemId + "' cols='50' name='comment' rows='1' placeholder='add comment'></textarea>";
                    line = line + "<input type='hidden' name='itemId' value=" + item.ItemId + ">";
                    line = line + "<input type='submit' value='submit'>";
                    line = line + "</form>";
                    line = line + "<div>";
                    line = line + "<div id='" + item.ItemId + "'></div>";
                    line = line + "</div>";
                    line = line + "</div></td></tr><tr><td><br><br></td></tr>";

                }
                target.append(line);
            },
            error: function (data) {
                alert(data);
            }
        });
    }


    window.onload = function () {
        document.getElementById('uploader').onsubmit = function () {
            var formdata = new FormData();
            var fileInput = document.getElementById('fileInput');
            for (i = 0; i < fileInput.files.length; i++) {
                formdata.append(fileInput.files[i].name, fileInput.files[i]);
            }
            var xhr = new XMLHttpRequest();
            xhr.open('POST', '/Home/Upload');
            xhr.send(formdata);
            xhr.onreadystatechange = function () {
                if (xhr.readyState == 4 && xhr.status == 200) {
                    location.reload();
                }
            }
            return false;
        }
    }


</script>


<br>
<br>

<div class="container">
    <div class="row">
        <div class="col-sm-10">
            <div id="profileWallPaper">
                <img width="800" height="300"  src="@Url.Action("GetWallpaper", "Home", new { Model.PersonId })" />
            </div>
                <div class="row">
                    <div class="col-sm-2" id="changePhoto">
                        <img width="145" height="130" class="img-rounded" src="@Url.Action("GetImage", "Home", new { Model.PersonId })" />
                        <div style="background-color: azure">
                            @Model.FirstName
                            @Model.LastName
                        </div>
                        <button class="btn btn-success btn-md" id="photoChange" style="display: none">Change photo</button>
                    </div>

                </div>
                <div class="row">
                    <div class="col-sm-4"></div>
                    <div class="col-sm-8">
                    </div>
                </div>


            <div class="row">
                <div class="row">
                    <div class="col-sm-3" id="personDetails">
                        <p><b>Birthday</b>: @Model.Birthday.Value.Date.ToString("dd MMMM yyyy") </p>
                    </div>
                    <div class="col-sm-6">


                        @if (ViewBag.IsFriendWith == true)
                        {
                            <button class="btn btn-success btn-md">Friend</button>
                        }
                        else
                        {
                            <button class="btn btn-success btn-md" id="friendRequest">Add to friends</button>
                        }
                        @Html.ActionLink("Message him", "Index", "Message", new { PersonId = Model.PersonId }, null)
                    </div>
                    <div class="col-sm-3">
                    </div>
                </div>
            </div>
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />

            @*            <div class="row">
                <div class="col-sm-3"></div>
                <div class="col-sm-8">
                    @using (Html.BeginForm("ShareItem", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <div class="row">
                            <div class="col-sm-9">
                                @Html.TextArea("Text", null, new { @class = "form-control", placeholder = "What is in your mind ?" })
                                <input type="file" class="filestyle" data-input="false" name="Image" />
                                @Html.DropDownList("shareOption", new[] {
                               new SelectListItem() {Text = "Public", Value = "Public"},
                               new SelectListItem() {Text = "Friends", Value = "Friends"},
                               new SelectListItem() {Text = "Only me", Value = "OnlyMe"}
                               })
                            </div>
                            <div class="col-sm-2">
                                <input class="form-control" type="submit" value="Post" />
                            </div>
                        </div> 
                    }
                </div>
            </div>*@

            <br>
            <br>
            <br>

            <div class="row">
                <div class="col-sm-3" id="sideDiv">
                    <input type="text" value="1" class="intro" style="display: none" />
                </div>
                <div class="col-sm-6" id="homeCenter">
                    <table>
                        <tbody id="sharedItem">
                        </tbody>
                    </table>
                </div>
                <div class="col-sm-3" id="rightDiv">
                </div>
            </div>

        </div>
    </div>
</div>